myapp/urls.py
from django.urls import path
from . import views

app_name= "myapp"
urlpatterns = [
    path('', views.index, name = "index"),
    path('products/', views.products, name = "products"),
    path('products/<int:id>/', views.product_detail, name = "product_detail"),
    path('products/add/', views.add_product, name = "add_product"),
    path('products/update/<int:id>/', views.update_product, name = "update_product"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models


class Product(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=300)
    image = models.ImageField(blank=True, upload_to="images")

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product


def index(req):
    return HttpResponse("<h1>Hello WOrld</h1>")


def products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'myapp/index.html', context)


def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }
    return render(request, 'myapp/detail.html', context)


def add_product(request):
    if request.method == "POST":
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        product = Product(name=name, price=price, desc=desc, image=image)
        product.save()

    return render(request, 'myapp/addproduct.html')


def update_product(request, id):
    product = Product.objects.get(id=id)
    if request.method == "POST":
        product.name = request.POST.get("name")
        product.price = request.POST.get("price")
        product.desc = request.POST.get("desc")
        if product.image:
            product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    context = {
        'product': product
    }
    return render(request, 'myapp/updateproduct.html', context)

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class ="text-2xl m-10 font-bold">➕ Add Product</h1>
    <form class ="bg-white shadow-md m-10 px-8 py-8 w-1/3" method="POST" enctype = "multipart/form-data">
            {% csrf_token %}
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder = "Name of product" type="text" name = "name" id="name">
        </div>
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder = "Price" type="text"name = "price" id="price">
        </div>
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder = "Description" type="text" name = "desc" id="desc">
        </div>
        <div class="mt-2">
            <label class ="block text-gray-700 text-sm font-bold" for="">Product Image</label>
            <input class = "py-2" type="file" accept="image/*" name = "upload" id="image">
        </div>
        <div class ="mt-2">
            <input class = "px-5 py-2 bg-green-500 text-white" type="submit" name ="Add Product" value ="Add Product">
        </div>

    </form>



 {% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <head>
            <link rel ="stylesheet" href="{% static 'myapp/styles.css' %}">
        </head>
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class ="flex justify-between">
                    <div class ="flex space-x-7 items-center">
                        <div>
                            <a href ="#"class ="flex px-2 py-4">
                            <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}" alt="logo">
                            <span class="text-yellow-500 text-lg font-black">Buy&Sell</span>
                            </a>
                        </div>
                        <div class ="items-center space-x-1">
                            <a href="#" class ="px-2 py-4 text-yellow-500 font-black text-lg border-b-4 border-green-500" >Home</a>
                            <a href="#" class ="px-2 py-4 text-yellow-500 font-black text-lg border-b-4 border-green-500">About</a>
                            <a href="#" class ="px-2 py-4 text-yellow-500 font-black text-lg border-b-4 border-green-500">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
       {% block content%}
       
       {% endblock %}
        
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block content %}

    <div class ="flex p-10 w-full h-200">
        <img class ="w-1/3" src="{{ product.image.url }}">
        <div class = 'w-2/3 text-xl ml-10 mt-10'>
            <div class ="mt-5">{{ product.name }}</div>
            <div class ="mt-5 text-green-500">$ {{ product.price }}</div>
            <div class = "mt-5 text-gray-700">{{ product.desc }}</div>
        </div>
        
    </div>
        
{% endblock %}
      

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg: mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl text-gray-900 font-extrabold sm:text-5xl md:text-6xl">
                <span class="block xl:inline">Premium Products</span>
                <span class ="block text-green-500 xl:inline">Premium Prices</span>
            </h1>
            <p class ="mt-3 text-base text-gray-500 sm:text-lg sm:mt-5 sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality products across the globe</p>
        </div>
    </main>

    <div class ="flex mt-5 p-10 justify-center">
        <h2 class ="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent products</h2>
    </div>
    <div class ="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg-grid-cols-3 gap-5">

    {% for product in products %}
    <a href="{% url 'myapp:product_detail' product.id %}">
        <div class ="rounded overflow-hidden shadow-lg">
            <img class = "w-full" src="{{ product.image.url }}" alt=""/>
            <div class ="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{ product.name }} </div>
                <div class ="font-bold text-green-500 mb-2">$ {{ product.price }}</div>
                <p class ="text-gray-700 text-base">{{ product.desc }}</p>
            </div>
        </div>
    </a>  
        {% endfor %}

    </div>

   
{% endblock content %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class ="text-2xl m-10 font-bold">➕ Update Product</h1>
    <form class ="bg-white shadow-md m-10 px-8 py-8 w-1/3" method="POST" enctype = "multipart/form-data">
            {% csrf_token %}
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder = "Name of product" value="{{product.name}}" type="text" name = "name" id="name">
        </div>
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value ="{{product.price}}" placeholder = "Price" type="text"name = "price" id="price">
        </div>
        <div class ="mb-2">
            <label class ="block text-gray-700 text-sm font-bold mb-2" for="">Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value = "{{product.desc}}" placeholder = "Description" type="text" name = "desc" id="desc">
        </div>
        <div class="mt-2">
            <img class ="h-20 w-20" src="{{product.image.url}}" alt="">
            <label class ="block text-gray-700 text-sm font-bold" for="">Product Image</label>
            <input class = "py-2" type="file" accept="image/*" name = "upload" id="image">
        </div>
        <div class ="mt-2">
            <input class = "px-5 py-2 bg-green-500 text-white" type="submit" name ="Edit Product" value ="Edit Product">
        </div>

    </form>



 {% endblock %}